# Generated by Django 3.2 on 2021-04-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disorder",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("disorder_name", models.CharField(max_length=100)),
                ("disorder_type_id", models.IntegerField()),
                ("disorder_type_name", models.CharField(max_length=100)),
                ("disorder_group_id", models.IntegerField()),
                ("disorder_group_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("term", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SymptomDisorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_name", models.CharField(max_length=100)),
                ("include_in_form", models.BooleanField(default=False)),
                (
                    "disorder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptoms.disorder",
                    ),
                ),
                (
                    "symptom_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptoms.symptom",
                    ),
                ),
            ],
        ),
    ]
