# Generated by Django 3.2 on 2021-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptoms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disorder",
            name="disorder_group_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="disorder_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="disorder_type_name",
            field=models.CharField(max_length=250),
        ),
    ]
