# Generated by Django 3.2 on 2021-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptoms", "0003_alter_symptomdisorder_frequency_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptom",
            name="term",
            field=models.CharField(max_length=250),
        ),
    ]
