# Generated by Django 3.2 on 2021-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptoms", "0005_symptomdisorder_frequency_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symptomdisorder",
            name="include_in_form",
        ),
        migrations.AddField(
            model_name="symptom",
            name="include_in_form",
            field=models.BooleanField(default=False),
        ),
    ]
